# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0412.175.1H

run:
  name: 'China-175'
  
foresight: "myopic" 
# foresight: "steady-state"
results_dir: 'results/'
summary_dir: 'summary/'

scenario:
  line_limits: [ 'opt' ]
  pathway: ['exponential175','beta25175']
  topology: "current+Neighbor" # "current" or "FCG" or "current+FCG" or "current+Neighbor"
  co2_reduction:
    exponential175:
      '2020': 0.0
      '2025': 0.22623418
      '2030': 0.41175086
      '2035': 0.56387834
      '2040': 0.688626
      '2045': 0.79092165
      '2050': 0.87480618
      '2055': 0.94359322
      '2060': 1.0
    linear175:
      '2020': 0.
      '2025': 0.16666667
      '2030': 0.33333333
      '2035': 0.5
      '2040': 0.66666667
      '2045': 0.83333333
      '2050': 1.0
      '2055': 1.0
      '2060': 1.0
    beta05175:
      '2020': 0.
      '2025': 0.41489656
      '2030': 0.5139467
      '2035': 0.58764476
      '2040': 0.65150003
      '2045': 0.71196579
      '2050': 0.77403968
      '2055': 0.84573191
      '2060': 1.0
    beta25175:
      '2020': 0.0 #0.
      '2025': 0.05096974 #0.06949544
      '2030': 0.23251132 #0.27330722
      '2035': 0.5 #0.52741596
      '2040': 0.76748868 #0.75163934
      '2045': 0.94903026 #0.90276156
      '2050': 1.0 #0.97687314
      '2055': 1.0 #0.99829624
      '2060': 1.0 #1.0
    mean175:
      '2020': 0.
      '2025': 0.12193339
      '2030': 0.29252381
      '2035': 0.53193917
      '2040': 0.75766462
      '2045': 0.88664452
      '2050': 0.93740309
      '2055': 0.97179661
      '2060': 1.0
  opts: ['ll']
  attr: 'p_nom'
  planning_horizons:
    - 2020
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050
    - 2055
    - 2060
  heating_demand: ['positive']

snapshots:
  start: "2020-01-01"
  end: "2021-01-01"
  inclusive: 'left'

tmin: '-01-01 00:00'
tmax: '-12-31 23:00'
freq: '1h'
frequency: 1.

logging_level: INFO
logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'
  
enable:
  build_cutout: false
  retrieve_cutout: false
  retrieve_raster: false
  
atlite:
  nprocesses: 4
  show_progress: true
  cutouts:
   China-2020:
     module: era5
     dx: 0.25
     dy: 0.25

solar_thermal_angle: 45

Technique:
  solar: true
  onwind: true
  offwind: true

coal_cc: true
hydrogen_lines: false

existing_infrastructure: ['coal','CHP coal', 'CHP gas', 'OCGT','solar', 'solar thermal', 'onwind', 'offwind','coal boiler','ground heat pump','nuclear']

bus_suffix: [""," central heat"," decentral heat"," gas"," coal"]
bus_carrier: {
    "": "AC",
    " central heat": "heat",
    " decentral heat": "heat",
    " gas": "gas",
    " coal": "coal",
}

Techs:
  ## for add carriers
  vre_techs: [ "onwind","offwind","solar","solar thermal","hydroelectricity", "nuclear","biomass","heat pump","resistive heater","Sabatier","H2 CHP"]
  conv_techs: ["OCGT gas", "CHP gas", "gas boiler","coal boiler","coal power plant","CHP coal"]
  store_techs: ["H2","battery","water tanks","PHS"]


## add components
heat_coupling: True
add_gas: True
add_coal: True
add_biomass: True
add_hydro: True
add_H2: True
add_methanation: True

solving:
  options:
#    clip_p_max_pu: 1.e-2
#    load_shedding: false
#    transmission_losses: 0
#    noisy_costs: false
#    skip_iterations: true
#    track_iterations: false
#    min_iterations: 4
#    max_iterations: 6
#    seed: 123
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: false
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: false
    track_iterations: false

  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/options/definitions.html#solver
      threads: 4
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-6
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
      DualReductions: 0
#      threads: 4
#      method: 2 # barrier
#      crossover: 0
#      BarConvTol: 1.e-6
#      Seed: 123
#      AggFill: 0
#      PreDual: 0
#      GURO_PAR_BARDENSETHRESH: 200
#      seed: 10              # Consistent seed for all plattforms
    gurobi-numeric-focus:
      name: gurobi
      NumericFocus: 3       # Favour numeric stability over speed
      method: 2             # barrier
      crossover: 0          # do not use crossover
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-4
      OptimalityTol: 1.e-4
      ObjScale: -0.5
      threads: 8
      Seed: 123
    gurobi-fallback:        # Use gurobi defaults
      name: gurobi
      crossover: 0
      method: 2             # barrier
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-5
      OptimalityTol: 1.e-5
      Seed: 123
      threads: 8
    cplex-default:
      threads: 4
      lpmethod: 4 # barrier
      solutiontype: 2 # non basic solution, ie no crossover
      barrier.convergetol: 1.e-5
      feasopt.tolerance: 1.e-6
    cbc-default: {} # Used in CI
    glpk-default: {} # Used in CI

  mem: 80000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2

no_lines: False
line_volume_limit_max: 5.e+15   #line_volume_limit is set = factor * max
line_cost_factor: 1

existing_capacities:
  grouping_years: [1980,1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019, 2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060]
  threshold_capacity: 1

